# Generated by Django 5.0.2 on 2024-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.CharField(max_length=256),
        ),
    ]
